version: '3.8'

services:
  inprogress_api_prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - JWT_SECRET=secretExample
      - GOOGLE_ID=idExample
      - GOOGLE_SECRET=secretExample
      - REDIRECT_URL=http://localhost:3000/auth/google/redirect
      - MAIL_HOST=Email Delivery Platform
      - MAIL_PORT=1234
      - MAIL_USER=userExample
      - MAIL_PASS=passwordExample
      # Adicione outras variáveis de ambiente aqui, se necessário
    volumes:
      - ./src:/app/src

  postgresql_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: inprogress
      POSTGRES_USER: exampleUser
      POSTGRES_PASSWORD: examplePassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: